### ISSUE TITLE
Optional operations

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/CallForwardingSignal#37]
**Problem description**
As we have 2 operations defined we can assume that some implementations will not provide both. In order to allow this we must add error code 501 Not Implemented as an error for both endpoint. This is defined in the guideline in the table [here](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#32-http-response-codes). 

**Possible evolution**
Add 501 error code

**Alternative solution**

**Additional context**

**Comment by FabrizioMoggio** [comment]
Similar discussion in the Edge Cloud WG for the TI API:

https://github.com/camaraproject/EdgeCloud/discussions/218#discussioncomment-9578300

**Comment by FabrizioMoggio** [comment]
According to : https://github.com/camaraproject/Commonalities/discussions/160#discussioncomment-9619925

Possible solution: is to use 404 (resource not found). We could define a new resource to support the new Intent (automatic mobility) and if it is not supported by the Operator's implementation the new endpoint for the new Intent returns 404.

**Comment by FabrizioMoggio** [comment]
according to: https://wiki.camaraproject.org/display/CAM/2024-07-02+CFS+Minutes

We will adopt a solution for the Alpha release. Even if the discussion in Commonalities is not closed.

**Comment by FabrizioMoggio** [comment]
Considering: https://github.com/camaraproject/Commonalities/discussions/160#discussioncomment-9945260

are we really sure we need endpoint two as optional?

**Comment by bigludo7** [comment]
Why not re-opening the 2 yaml option in this case?
I solves the problem, we have UC for both, and it did no slow dow api adoption?

As we discussed in the past the UC are distinct for the use of this 2 endpoints. As such it is perfectly valid for a company to only need to solve one UC and not the other.

**Comment by FabrizioMoggio** [comment]
we need to maintain two YAMLs :-). Is this worthen? 

This is the current situation:

First of all we need to be sure if we want to have some operation as optional. This can be for technical or business reasons.

Second if we go for "optional" we have the following options (under discussion  here: https://github.com/camaraproject/Commonalities/discussions/160#). I summarize them here, with no comment, just for alignment:

1. optional endpoint not implemented, access denial to the operation in the authentication in the authorization flow
2. optional endpoint implemented but void, just returning an error code ("operation not supported")
3. One YAML for each operation

**Comment by FabrizioMoggio** [comment]
My personal position:

I don't see any technical or business reason strong enough to justify the burden.  

If we decide to have and endpoint as optional we must follow what it will be defined in Commonalities. 

Anyway my personal preference goes to option 2. I see it easier to document and to explain to the Developer with respect to option 1 and it is easier to maintain with respect to option 3.

**Comment by bigludo7** [comment]
For me as we have UC that work only with one of them they should be optional. As as as I know, our anti fraud UC that was btw the one initially triggering our work, requires only unconditional -- right?

Regarding the option we circle back & forth for month in device status before to move to distinct yaml. Same issue but distinct outcome in SIM Swap (one yaml - 2 endpoints). We did not have a clear answer in Commonalities - Why not getting TSC view on this ? @hdamker do you think we can get have opinion in TSC?

**Comment by FabrizioMoggio** [comment]
@bigludo7 I see your point on linking the endpoints to the Use Cases. So it is a business reason driving us to go for the "optional" approach. I also support to your proposal to escalate to TSC.

**Comment by FabrizioMoggio** [comment]
just to better understand you view, what is the drawback you see in option 2?

**Comment by hdamker** [comment]
@bigludo7 @FabrizioMoggio I support the proposal to bring the topic - in a generic form - into the TSC. It's about "atomic" versus "combined" APIs with optional supported endpoints. Would be good to have an issue with a problem statement and a solution proposal (or multiple options) within https://github.com/camaraproject/Governance. If possible also with a proposal where and how to document the result (ProjectCharter? Guideline in Commonalities?).

My personal preference are atomic APIs which are completely implemented. The main reasons is for me that otherwise an aggregation across operators is hard to achieve. The effort to maintain multiple YAML files can step by step be reduced by more automation.

**Comment by FabrizioMoggio** [comment]
Considering our time plan for the API development, to join Fall24 (https://github.com/camaraproject/CallForwardingSignal/discussions/38#discussioncomment-9956183)

And considering the agreement in the last call (https://wiki.camaraproject.org/display/CAM/2024-07-02+CFS+Minutes): "Optional Operation: the discussion Commonalities is not yet closed, anyway we will adopt a solution for Alpha with the proper documentation"

We should anyway move forward with a temporary solution. Considering the current feedbacks in this discussion and in https://github.com/camaraproject/Commonalities/discussions/160#, my feeling is that the must supported options are:

1. two YAMLs
2. authorization denial

I suggest to choose, at this stage, the one minimizing the effort, while we wait for the TSC to take a decision. In my understanding "option 2" is the easiest to adopt also considering that if we go for the "501" option, that is anyway in the Guidelines :-), "option 2" it is easiest to move in that direction.

So I suggest to temporarily  adopt option 2 (authorization denial).

**Comment by bigludo7** [comment]
@hdamker I can do it at least to illustrate the issue &  list proposal to solve it. I guess the result could be also impact the API backlog (when we deide for a new API we can discuss this)

@FabrizioMoggio I support your proposal... as it was mi initial proposal to add this 501 :)

**Comment by FabrizioMoggio** [comment]
Implemented with: https://github.com/camaraproject/CallForwardingSignal/pull/48

**Comment by FabrizioMoggio** [comment]
implemented with 0.2.0-rc.1
