### ISSUE TITLE
Changelog and Release Tag

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/CallForwardingSignal#61]
**Problem description**
the changelog file should have a reference to the release tag and not to the release branch in the "Table of contents" and in the links.

example: https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/CHANGELOG_EXAMPLE.md

the same for the readme.md file

**Expected behavior**
update the changelog.md and readme.md files

**Comment by hdamker** [comment]
@FabrizioMoggio Yes, there is no need to create an additional release branch anymore. 

And please use as release tag the simple "r1.1". This release contains the API **version** v0.2.0-rc.1, but the release numbering is independent of the API Version.

**Comment by FabrizioMoggio** [comment]
implemented with: https://github.com/camaraproject/CallForwardingSignal/pull/62
