### ISSUE TITLE
Align info.description Auth section with ICM 0.2.0-rc.2

### ISSUE THREAD

**Issue by hdamker** [camaraproject/CallForwardingSignal#90]
**Problem description**

The mandatory text for info.description about "Authorization and authentication" got update in ICM 0.2.0, latest in r0.2.0-rc.2 with https://github.com/camaraproject/IdentityAndConsentManagement/pull/186. 

**Expected behavior**

Update the text within info.description with the latest text version from https://github.com/camaraproject/IdentityAndConsentManagement/blob/r0.2.0-rc.2/documentation/CAMARA-API-access-and-user-consent.md#mandatory-template-for-infodescription-in-camara-api-specs

**Alternative solution**

**Additional context**

**Comment by FabrizioMoggio** [comment]
Fixed with: https://github.com/camaraproject/CallForwardingSignal/pull/91

https://github.com/camaraproject/CallForwardingSignal/pull/91/commits/3b72d16816dc5049802a0b3a1531c1a1df442b4f

**Comment by FabrizioMoggio** [comment]
Merged
