### ISSUE TITLE
Convention for file names of API definition

### ISSUE THREAD

**Issue by rartych** [camaraproject/CallForwardingSignal#93]
**Problem description**
There is currently no guidelines for file names of API definition files in CAMARA.
The initially agreed proposal is to use the convention `api-name.yaml` as a guideline for the API definition file names.

**Expected behavior**
Change the file name to `call-forwarding-signal.yaml` before or as a part of release PR for M4.

**Alternative solution**
Wait for the final guidelines.

**Additional context**
See the discussion in [Commonalities](https://github.com/camaraproject/Commonalities/issues/284).

**Comment by FabrizioMoggio** [comment]
Proposal: rename the file as part of the PR for M4

**Comment by bigludo7** [comment]
Same than @FabrizioMoggio 
Let's change name for the M4

**Comment by FabrizioMoggio** [comment]
Fixed with: https://github.com/camaraproject/CallForwardingSignal/pull/95

**Comment by FabrizioMoggio** [comment]
Fixed with: https://github.com/camaraproject/CallForwardingSignal/pull/101
